name: horizon
display_name: Horizon
desc: The new default Liquid theme for Shopify Online Stores
type: web
up:
  - node:
      version: v22.14.0
commands:
  server:
    desc: "Run shopify theme dev"
    run: npm run dev
